### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by Achie72** [Achie72/flappy_ducky#3]
A better update could be used for much better presentation.
See example in [Neon Runner](https://github.com/Achie72/neon-runner)

Image could be grabbed from the [itch.io](https://achie.itch.io/flappy-ducky) site with:

`![alt text](link)` format, such as below:

![alt text](
https://img.itch.zone/aW1hZ2UvNTYxMTM0LzI5NDUwNTIuZ2lm/347x500/IsV0Rj.gif)

**Comment by kisbg** [comment]
Hi Achie72 ! I created a pull request based on the issue :)
 #4
